# Generated by Django 3.1.4 on 2020-12-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(null=True)),
                ('distanceTotal', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('mphi', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('d_mp5', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('d_mphi', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('velMayor16', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('velEntre16y20', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('velEntre20y25', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('deceleration', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('mpmi', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('velMax', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('totalTime', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('eee', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportista.deportista')),
            ],
        ),
    ]
