# Generated by Django 3.1.4 on 2021-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoobjetivo', '0002_auto_20201230_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoobjetivo',
            name='velMayor25',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
