# Generated by Django 3.1.4 on 2021-03-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datoobjetivo', '0004_auto_20210223_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoobjetivo',
            old_name='velMayor16',
            new_name='velMenor16',
        ),
    ]
