# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'verbose_name_plural': 'Enfermedades'},
        ),
    ]
