# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': 'Instituciones'},
        ),
    ]
