# Generated by Django 3.1.4 on 2021-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0002_auto_20201230_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='documento',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
