# Generated by Django 3.1.4 on 2020-12-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoSubjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('inpregunta1', models.CharField(max_length=50, null=True)),
                ('inpregunta2', models.CharField(max_length=50, null=True)),
                ('inpregunta2a', models.CharField(max_length=50, null=True)),
                ('inpregunta3', models.CharField(max_length=50, null=True)),
                ('inpregunta4', models.CharField(max_length=50, null=True)),
                ('colorIn', models.CharField(choices=[('VE', 'Verde'), ('RO', 'Rojo'), ('AM', 'Amarillo')], default='VE', max_length=2)),
                ('outpregunta1', models.CharField(max_length=50, null=True)),
                ('colorOut', models.CharField(choices=[('VE', 'Verde'), ('RO', 'Rojo'), ('AM', 'Amarillo')], default='VE', max_length=2)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportista.deportista')),
            ],
        ),
    ]
