# Generated by Django 3.1.4 on 2020-12-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0002_auto_20201226_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'verbose_name_plural': 'Permisos'},
        ),
    ]
